# =====================================================================================
# SHARED LunarWerx tray SHORTCUT engine (Windows PowerShell). One parameterized function that
# creates / refreshes an app's root .lnk pointing at the shared Tray-Launch.vbs — the superset
# evolution of the four near-identical per-app Create-Shortcut.ps1 scripts. Each app's
# Create-Shortcut.ps1 is now a THIN ADAPTER: it dot-sources this file and calls New-TrayShortcut
# with just its own name / icon / description / legacy-lnk cleanup list.
#
# SHARED — source of truth: lunarwerx-ui/src/tray-host/New-TrayShortcut.ps1; synced into each
# app's misc/ by sync.mjs, alongside Tray-Host.ps1 / Tray-Launch.vbs / the <App>-Tray.ps1 adapter.
# DO NOT EDIT THIS FILE INSIDE AN APP — edit the kit copy and run `node sync.mjs`.
#
# Runs under Windows PowerShell 5.1 (powershell.exe) — no PS7-only syntax.
#
# Why one engine: the four Create-Shortcut.ps1 were identical except each app's display name,
# icon, description, and (ReDesign only) a non-ASCII shortcut label plus a legacy-.lnk cleanup
# list. Extracting the shared body means a fix lands once and syncs everywhere; every WHY-comment
# from the originals (in particular ReDesign's macron / ANSI-save dance) is preserved below.
# =====================================================================================

function New-TrayShortcut {
  # -Root        Project root — where the .lnk lives and the shortcut's WorkingDirectory.
  # -ScriptDir   The app's misc/ dir — holds Tray-Launch.vbs and the icon.
  # -LnkName     Shortcut label WITHOUT ".lnk" (the name users SEE under the icon). MAY contain
  #              non-ASCII (e.g. 'RēDesign' with U+0113) — handled via the ASCII-temp dance below.
  # -IconFile    Icon filename inside ScriptDir (e.g. 'Reimagine.ico').
  # -Description The .lnk Description tooltip. MUST be pure ASCII (see the ANSI note below).
  # -VbsFile     The launcher the shortcut runs (default the shared 'Tray-Launch.vbs').
  # -LegacyLnks  Old .lnk BASE names (with or without .lnk) to delete from Root so a rename/history
  #              doesn't leave the user with duplicate shortcuts. Best-effort.
  param(
    [Parameter(Mandatory = $true)] [string]   $Root,
    [Parameter(Mandatory = $true)] [string]   $ScriptDir,
    [Parameter(Mandatory = $true)] [string]   $LnkName,
    [Parameter(Mandatory = $true)] [string]   $IconFile,
    [Parameter(Mandatory = $true)] [string]   $Description,
    [string]   $VbsFile = 'Tray-Launch.vbs',
    [string[]] $LegacyLnks = @()
  )

  $finalLnk = Join-Path $Root ($LnkName + '.lnk')

  # Does the label contain any non-ASCII char (code point > 127)? WScript.Shell saves the .lnk
  # through an ANSI path, so it can only WRITE to an ASCII filename — a Unicode target name is
  # silently transliterated (e.g. ē -> e). So for a non-ASCII label we save to a plain-ASCII temp
  # name, then rename to the real name via the Unicode filesystem API (Move-Item), which preserves
  # it (NTFS stores filenames as UTF-16, so the macron/accent survives there). A pure-ASCII label
  # needs none of that — we save straight to the final path.
  $isAscii = $true
  foreach ($ch in $LnkName.ToCharArray()) { if ([int][char]$ch -gt 127) { $isAscii = $false; break } }

  # An ASCII-only sibling name for the temp save (strip any non-ASCII char). Used only on the
  # non-ASCII path; a pure-ASCII label writes to $finalLnk directly (no temp, no rename).
  if ($isAscii) {
    $tmpLnk = $finalLnk
  } else {
    $asciiBase = -join ($LnkName.ToCharArray() | Where-Object { [int][char]$_ -le 127 })
    if (-not $asciiBase) { $asciiBase = 'TrayShortcut' }
    $tmpLnk = Join-Path $Root ($asciiBase + '.lnk')
  }

  # Best-effort cleanup: any legacy .lnk names (supersedes older pre-rename shortcuts), the ASCII
  # temp, and the final target — so a re-run never leaves the owner with duplicate/stale shortcuts.
  $toRemove = @($finalLnk, $tmpLnk)
  foreach ($n in $LegacyLnks) {
    $bn = $n
    if (-not $bn.ToLower().EndsWith('.lnk')) { $bn = $bn + '.lnk' }
    $toRemove += (Join-Path $Root $bn)
  }
  foreach ($p in ($toRemove | Select-Object -Unique)) {
    if (Test-Path -LiteralPath $p) { try { Remove-Item -LiteralPath $p -Force } catch {} }
  }

  $ws = New-Object -ComObject WScript.Shell
  $sc = $ws.CreateShortcut($tmpLnk)
  # Run the .vbs through wscript explicitly (no console window, no file-association surprises).
  $sc.TargetPath = Join-Path $env:SystemRoot "System32\wscript.exe"
  $sc.Arguments  = '"' + (Join-Path $ScriptDir $VbsFile) + '"'
  $sc.WorkingDirectory = $Root
  $sc.IconLocation = (Join-Path $ScriptDir $IconFile) + ",0"
  # WScript.Shell's .lnk Description property is ANSI-limited and silently drops non-ASCII (ē
  # becomes e), so callers pass the plain-ASCII form here rather than have it disagree with the
  # filename. (The filename above carries the accent; the Description can't.)
  $sc.Description = $Description
  $sc.Save()

  # Non-ASCII label only: rename the saved ASCII shortcut to the real name. Renaming does not touch
  # the .lnk's internal TargetPath / IconLocation, so the shortcut keeps working. (ASCII label saved
  # straight to $finalLnk, so $tmpLnk -eq $finalLnk and there is nothing to move.)
  if ($tmpLnk -ne $finalLnk) {
    Move-Item -LiteralPath $tmpLnk -Destination $finalLnk -Force
  }
  Write-Host "Created shortcut: $finalLnk"
}
